global using Cogs.Collections;
global using LiftDataManager.Core.DataAccessLayer.Models;
global using LiftDataManager.Core.DataAccessLayer.Models.AllgemeineDaten;
global using LiftDataManager.Core.Enums;
global using LiftDataManager.Core.Helpers;
global using LiftDataManager.Core.Models;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using System.Text;
