// -----------------------------------------------------------------------------------------------------
// | <auto-generated>                                                                                  |
// |    This code was generated by a tool.                                                             |
// |                                                                                                   |
// |    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. |
// | </auto-generated>                                                                                 |
// -----------------------------------------------------------------------------------------------------

// Define JSON file path variable for easy adjustment

namespace LiftDataManager;
public partial class NavigationPageMappings
{
    public static Dictionary<string, Type> PageDictionary { get; } = new Dictionary<string, Type>
    {
        {"LiftDataManager.Views.HomePage", typeof(LiftDataManager.Views.HomePage)},
        {"LiftDataManager.Views.AllgemeineDatenPage", typeof(LiftDataManager.Views.AllgemeineDatenPage)},
        {"LiftDataManager.Views.SchachtPage", typeof(LiftDataManager.Views.SchachtPage)},
        {"LiftDataManager.Views.KabinePage", typeof(LiftDataManager.Views.KabinePage)},
        {"LiftDataManager.Views.BausatzPage", typeof(LiftDataManager.Views.BausatzPage)},
        {"LiftDataManager.Views.TürenPage", typeof(LiftDataManager.Views.TürenPage)},
        {"LiftDataManager.Views.AntriebSteuerungNotrufPage", typeof(LiftDataManager.Views.AntriebSteuerungNotrufPage)},
        {"LiftDataManager.Views.SignalisationPage", typeof(LiftDataManager.Views.SignalisationPage)},
        {"LiftDataManager.Views.WartungMontageTüvPage", typeof(LiftDataManager.Views.WartungMontageTüvPage)},
        {"LiftDataManager.Views.SonstigesPage", typeof(LiftDataManager.Views.SonstigesPage)},
        {"LiftDataManager.Views.EinreichunterlagenPage", typeof(LiftDataManager.Views.EinreichunterlagenPage)},
        {"LiftDataManager.Views.KabinengewichtPage", typeof(LiftDataManager.Views.KabinengewichtPage)},
        {"LiftDataManager.Views.NutzlastberechnungPage", typeof(LiftDataManager.Views.NutzlastberechnungPage)},
        {"LiftDataManager.Views.StructureLoadsPage", typeof(LiftDataManager.Views.StructureLoadsPage)},
        {"LiftDataManager.Views.KabinenLüftungPage", typeof(LiftDataManager.Views.KabinenLüftungPage)},
        {"LiftDataManager.Views.SchachtDetailPage", typeof(LiftDataManager.Views.SchachtDetailPage)},
        {"LiftDataManager.Views.KabineDetailPage", typeof(LiftDataManager.Views.KabineDetailPage)},
        {"LiftDataManager.Views.KabineDetailEquipmentPage", typeof(LiftDataManager.Views.KabineDetailEquipmentPage)},
        {"LiftDataManager.Views.KabineDetailFloorPage", typeof(LiftDataManager.Views.KabineDetailFloorPage)},
        {"LiftDataManager.Views.KabineDetailLayoutPage", typeof(LiftDataManager.Views.KabineDetailLayoutPage)},
        {"LiftDataManager.Views.KabineDetailCeilingPage", typeof(LiftDataManager.Views.KabineDetailCeilingPage)},
        {"LiftDataManager.Views.KabineDetailControlPanelPage", typeof(LiftDataManager.Views.KabineDetailControlPanelPage)},
        {"LiftDataManager.Views.BausatzDetailPage", typeof(LiftDataManager.Views.BausatzDetailPage)},
        {"LiftDataManager.Views.BausatzDetailRailBracketPage", typeof(LiftDataManager.Views.BausatzDetailRailBracketPage)},
        {"LiftDataManager.Views.ListenansichtPage", typeof(LiftDataManager.Views.ListenansichtPage)},
        {"LiftDataManager.Views.DatenansichtPage", typeof(LiftDataManager.Views.DatenansichtPage)},
        {"LiftDataManager.Views.TabellenansichtPage", typeof(LiftDataManager.Views.TabellenansichtPage)},
        {"LiftDataManager.Views.LiftHistoryPage", typeof(LiftDataManager.Views.LiftHistoryPage)},
        {"LiftDataManager.Views.AbbreviationPage", typeof(LiftDataManager.Views.AbbreviationPage)},
        {"LiftDataManager.Views.DataBaseEditPage", typeof(LiftDataManager.Views.DataBaseEditPage)},
        {"LiftDataManager.Views.QuickLinksPage", typeof(LiftDataManager.Views.QuickLinksPage)},
        {"LiftDataManager.Views.HelpPage", typeof(LiftDataManager.Views.HelpPage)},
        {"LiftDataManager.Views.AboutSettingPage", typeof(LiftDataManager.Views.AboutSettingPage)},
        {"LiftDataManager.Views.GeneralSettingPage", typeof(LiftDataManager.Views.GeneralSettingPage)},
        {"LiftDataManager.Views.MaintenanceSettingPage", typeof(LiftDataManager.Views.MaintenanceSettingPage)},
        {"LiftDataManager.Views.ThemeSettingPage", typeof(LiftDataManager.Views.ThemeSettingPage)},
    };
}
